/* papicture — catalog data (looks + formats).
   Model: photos are sold as DIGITAL files (cheap) or PRINTED SETS by copy count,
   the way every PH photo shop actually sells them.
   Ported from the design bundle; `px` target dimensions added for real rendering. */

import type { Look, Format, Swatch, Group } from './types';

export const LOOKS: Look[] = [
  {
    id: 'original', name: 'As is', code: 'LK-01',
    tagline: 'Keep my outfit, just cleaner.',
    desc: 'Your current clothes, with a tidy background and even studio light. The lowest-risk option.',
    sub: null,
    best: 'Quick IDs, casual profiles, clothing-sensitive forms',
  },
  {
    id: 'smartcasual', name: 'Smart casual', code: 'LK-02',
    tagline: 'Neat and presentable.',
    desc: 'A clean, presentable top. Plain shirt or a collared polo, tidy without looking stiff.',
    sub: { label: 'Top', options: ['Plain white tee', 'Plain black tee', 'Collared polo', 'Button-down'] },
    best: 'School IDs, work IDs, résumés',
  },
  {
    id: 'formal', name: 'Formal', code: 'LK-03',
    tagline: 'Studio headshot energy.',
    desc: 'Blazer, suit, professional blouse or barong. Realistic attire, not a corporate avatar.',
    sub: { label: 'Attire', options: ['Dark blazer + white shirt', 'Business suit', 'Professional blouse', 'Barong'] },
    best: 'Company ID, résumé, LinkedIn, business profile',
  },
  {
    id: 'docsafe', name: 'Document-safe', code: 'LK-04',
    tagline: 'Crop, resize and background only.',
    desc: 'Background, crop and light exposure only. No retouching, reshaping or outfit changes — so it stays true to your real photo.',
    sub: null,
    best: 'Visa and passport-style formats',
  },
];

// background swatch palette
export const BG: Record<string, Swatch> = {
  white:   { id: 'white',   name: 'White',      hex: '#ffffff', ring: '#e2e5ea' },
  offwhite:{ id: 'offwhite',name: 'Off-white',  hex: '#f4f2ec', ring: '#e6e2d6' },
  blue:    { id: 'blue',    name: 'Blue',       hex: '#2f6fd0', ring: '#2f6fd0' },
  red:     { id: 'red',     name: 'Red',        hex: '#c23b34', ring: '#c23b34' },
  ltgray:  { id: 'ltgray',  name: 'Light gray', hex: '#e9eaec', ring: '#d6d8dc' },
  warmgray:{ id: 'warmgray',name: 'Warm gray',  hex: '#e6e1da', ring: '#d6d0c6' },
  softblue:{ id: 'softblue',name: 'Soft blue',  hex: '#dbe6f2', ring: '#c3d4e8' },
  neutral: { id: 'neutral', name: 'Neutral',    hex: '#eceae6', ring: '#dcd9d3' },
};

// strictness → chip class
export const STRICT: Record<string, { label: string; cls: string }> = {
  flexible: { label: 'Flexible', cls: 'pa-chip-flexible' },
  standard: { label: 'Document', cls: 'pa-chip-accent' },
  strict:   { label: 'Document', cls: 'pa-chip-accent' },
};

export const FORMATS: Format[] = [
  // ---------- Group A — ID photo sets ----------
  { group: 'ID photo sets', groupCode: 'A',
    id: '2x2', name: '2×2 Set', short: '2×2', code: 'SET-2X2',
    size: '6 pcs 2×2', unit: '2 × 2 in', ratio: 1,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'Work and school requirements, government-style forms',
    digital: true, print: true,
    printSet: '6 pcs 2×2', printPrice: 199,
    digitalSpec: '2×2 in · 600×600 px JPG', px: [600, 600] },
  { group: 'ID photo sets', groupCode: 'A',
    id: '1.5x1.5', name: '1.5×1.5 Set', short: '1.5×1.5', code: 'SET-15',
    size: '8 pcs 1.5×1.5', unit: '1.5 × 1.5 in', ratio: 1,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'School and office IDs, NBI, general forms',
    digital: true, print: true,
    printSet: '8 pcs 1.5×1.5', printPrice: 199,
    digitalSpec: '1.5×1.5 in · 600×600 px JPG', px: [600, 600] },
  { group: 'ID photo sets', groupCode: 'A',
    id: '1x1', name: '1×1 Set', short: '1×1', code: 'SET-1X1',
    size: '8 pcs 1×1', unit: '1 × 1 in', ratio: 1,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'School, office and club forms, general ID',
    digital: true, print: true,
    printSet: '8 pcs 1×1', printPrice: 199,
    digitalSpec: '1×1 in · 600×600 px JPG', px: [600, 600] },
  { group: 'ID photo sets', groupCode: 'A',
    id: 'pp-set', name: 'Passport Set', short: 'Passport 35×45', code: 'SET-PP',
    size: '6 pcs 35×45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white','offwhite'], defaultBg: 'white',
    strict: 'standard', looks: ['docsafe','smartcasual'],
    best: 'Visa, NBI clearance and school requirements',
    digital: true, print: true,
    printSet: '6 pcs 35×45 mm', printPrice: 199,
    digitalSpec: '35×45 mm · 600×750 px JPG', px: [600, 750],
    warn: 'Philippine ePassport photos are taken at the DFA. Use this set for visas, NBI and school — not the DFA appointment itself.' },
  // combos — sold by the set, like the local shop's combo packages
  { group: 'ID photo sets', groupCode: 'A',
    id: 'mix', name: '2×2 + 1×1 Combo', code: 'SET-MIX',
    size: '4 pcs 2×2 + 4 pcs 1×1', unit: '2×2 in + 1×1 in', ratio: 0.77,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'Covers both sizes most forms ask for',
    digital: false, print: true, sheet: true, combo: true,
    printSet: '4 pcs 2×2 + 4 pcs 1×1', printPrice: 249, save: 149 },
  { group: 'ID photo sets', groupCode: 'A',
    id: 'mix-pp', name: 'Passport + 1×1 Combo', code: 'SET-MIXPP',
    size: '4 pcs 35×45 mm + 4 pcs 1×1', unit: '35×45 mm + 1×1 in', ratio: 0.77,
    backgrounds: ['white','offwhite'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'Passport-size plus 1×1 for forms in one go',
    digital: false, print: true, sheet: true, combo: true,
    printSet: '4 pcs 35×45 mm + 4 pcs 1×1', printPrice: 249, save: 149 },
  { group: 'ID photo sets', groupCode: 'A',
    id: 'mix-15', name: '1.5×1.5 + 1×1 Combo', code: 'SET-MIX15',
    size: '4 pcs 1.5×1.5 + 4 pcs 1×1', unit: '1.5×1.5 in + 1×1 in', ratio: 0.77,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'The two sizes school and office forms ask for',
    digital: false, print: true, sheet: true, combo: true,
    printSet: '4 pcs 1.5×1.5 + 4 pcs 1×1', printPrice: 249, save: 149 },
  { group: 'ID photo sets', groupCode: 'A',
    id: 'mix-3', name: '2×2 + 1×1 + Passport Combo', code: 'SET-MIX3',
    size: '4 pcs 2×2 + 2 pcs 1×1 + 2 pcs 35×45 mm', unit: '2×2 + 1×1 + 35×45 mm', ratio: 0.77,
    backgrounds: ['white','blue','red'], defaultBg: 'white',
    strict: 'flexible', looks: ['original','smartcasual','formal'],
    best: 'Every common size in a single set',
    digital: false, print: true, sheet: true, combo: true,
    printSet: '4 pcs 2×2 + 2 pcs 1×1 + 2 pcs 35×45 mm', printPrice: 349, save: 248 },

  // ---------- Group B — Profile & résumé ----------
  { group: 'Profile & résumé', groupCode: 'B',
    id: 'studio', name: 'Studio Portrait', code: 'PRO-STU',
    size: 'Digital, square & portrait', unit: 'Digital', ratio: 0.82,
    backgrounds: ['white','ltgray','warmgray','softblue','neutral'], defaultBg: 'neutral',
    strict: 'flexible', looks: ['smartcasual','formal'],
    best: 'Email, Slack and Teams, personal profile',
    digital: true, print: false,
    digitalSpec: '1080×1080 px + 1080×1350 px', px: [1080, 1350] },
  { group: 'Profile & résumé', groupCode: 'B',
    id: 'linkedin', name: 'LinkedIn / Résumé', code: 'PRO-LNK',
    size: 'Square, 4:5, circular crop', unit: 'Digital', ratio: 0.82,
    backgrounds: ['white','ltgray','softblue','neutral'], defaultBg: 'ltgray',
    strict: 'flexible', looks: ['smartcasual','formal'],
    best: 'CV, LinkedIn, portfolio, work profile',
    digital: true, print: false, circleOption: true,
    digitalSpec: '1080×1080 px · square & circle', px: [1080, 1080] },

  // ---------- Group C — Visa ----------
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'us-visa', name: 'US Visa', code: 'VS-USA',
    size: '2 × 2 in · 51 × 51 mm', unit: '2 × 2 in', ratio: 1,
    backgrounds: ['white','offwhite'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'US visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '600×600 px JPG · under 240 KB', px: [600, 600],
    rules: ['No glasses', 'Neutral expression', 'No retouching', 'No facial alteration', 'No generated outfit'],
    warn: 'For visas we crop, resize and fix the background only. Your face is not changed.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'jp-visa', name: 'Japan Visa', code: 'VS-JPN',
    size: '35 × 45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Japan visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '35×45 mm · 600×750 px JPG', px: [600, 750],
    rules: ['No digital modification', 'No facial alteration', 'No generated outfit', 'Crop / resize / bg only'],
    warn: 'Japan accepts crop and resize only, so that is all we do here.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'schengen-visa', name: 'Schengen Visa', code: 'VS-SCH',
    size: '35 × 45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white','ltgray'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Schengen visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '35×45 mm · 600×750 px JPG', px: [600, 750],
    rules: ['Head 70–80% of frame', 'Neutral expression', 'No heavy retouching', 'No facial alteration'],
    warn: 'Schengen rules vary by country. Check your appointment instructions for the exact size.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'ca-trv', name: 'Canada Visitor / TRV', code: 'VS-CAV',
    size: '≥ 35 × 45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white','ltgray'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Canada visitor visa / TRV',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '420×540 px or larger', px: [420, 540],
    rules: ['Head 31–36 mm chin→crown', 'Full front view', 'Face centered', 'Shoulders visible'],
    warn: 'Head height is 31–36 mm from chin to crown.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'ca-pr', name: 'Canada PR / Immigration', code: 'VS-CAP',
    size: '50 × 70 mm', unit: '50 × 70 mm', ratio: 0.714,
    backgrounds: ['white'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Canada PR / immigration photo',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '715×1000 px JPG/PNG', px: [715, 1000],
    rules: ['Head 31–36 mm chin→crown', 'Plain white only', 'Full front view'],
    warn: 'This is 50 × 70 mm — a different size from the visitor visa.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'cn-visa', name: 'China Visa', code: 'VS-CHN',
    size: '33 × 48 mm', unit: '33 × 48 mm', ratio: 0.688,
    backgrounds: ['white','offwhite'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'], darkTop: true,
    best: 'China visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '33×48 mm · 600×800 px JPG', px: [600, 800],
    rules: ['Colored / dark top', 'Avoid white top', 'Front-facing', 'No retouching'],
    warn: 'China visas need a dark or colored top and a 33 × 48 mm size.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'kr-visa', name: 'Korea Visa', code: 'VS-KOR',
    size: '35 × 45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Korea visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '35×45 mm · 600×750 px JPG', px: [600, 750],
    rules: ['Front-facing', 'Neutral expression', 'No hat', 'No heavy retouching'],
    warn: 'Korea rules vary by application center. Check the latest instructions.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'au-visa', name: 'Australia Passport / Visa', code: 'VS-AUS',
    size: '35–40 × 45–50 mm', unit: '35–40 × 45–50 mm', ratio: 0.8,
    backgrounds: ['white','ltgray'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Australia passport / visa-style',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '35–40 × 45–50 mm · 600×750 px', px: [600, 750],
    rules: ['Head 32–36 mm chin→crown', 'Neutral expression', 'Mouth closed', 'True likeness'],
    warn: 'Neutral expression with mouth closed.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'sa-visa', name: 'Saudi Visa', code: 'VS-SAU',
    size: '2 × 2 in · 51 × 51 mm', unit: '2 × 2 in', ratio: 1,
    backgrounds: ['white'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Saudi work / visit visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '2×2 in · 600×600 px JPG', px: [600, 600],
    rules: ['White background', 'Front-facing', 'Neutral expression', 'No retouching'],
    warn: 'Saudi visas use a 2 × 2 in photo on a white background.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'uk-visa', name: 'UK Visa', code: 'VS-GBR',
    size: '35 × 45 mm', unit: '35 × 45 mm', ratio: 0.778,
    backgrounds: ['white','ltgray'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'UK visitor / study / work visa application',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '35×45 mm · 600×750 px JPG', px: [600, 750],
    rules: ['Plain light background', 'Neutral expression', 'No glasses', 'No facial alteration'],
    warn: 'UK applications often take a digital upload. We size to spec; check your online instructions.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'hk-passport', name: 'Hong Kong Passport', code: 'VS-HKG',
    size: '40 × 50 mm', unit: '40 × 50 mm', ratio: 0.8,
    backgrounds: ['white','offwhite'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Hong Kong passport / visa-style photo',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '40×50 mm · 600×750 px JPG', px: [600, 750],
    rules: ['Plain light background', 'Front-facing', 'Neutral expression', 'No retouching'],
    warn: 'Hong Kong uses a 40 × 50 mm photo. Check your form for the exact requirement.' },
  { group: 'Visa & Passport', groupCode: 'C',
    id: 'ph-passport', name: 'Philippine Passport', short: 'PH Passport', code: 'VS-PHL',
    size: '4.5 × 3.5 cm', unit: '45 × 35 mm', ratio: 0.778,
    backgrounds: ['white'], defaultBg: 'white',
    strict: 'strict', looks: ['docsafe'],
    best: 'Passport-size requirement on forms',
    digital: true, print: true, printSet: '6 copies', printPrice: 249,
    digitalSpec: '45×35 mm · 600×750 px JPG', px: [600, 750],
    rules: ['Plain white background', 'Front-facing', 'Neutral expression', 'No retouching'],
    warn: "Philippine ePassport photos are taken at the DFA appointment. Use this for forms that ask for a passport-size photo, not the DFA appointment itself." },
];

export const GROUPS: Group[] = [
  { code: 'A', name: 'ID photo sets', note: 'Printed sets, cut and delivered', noteDigital: 'One file per size, ready to upload or print' },
  { code: 'B', name: 'Profile & résumé', note: 'Headshots for your digital life', noteDigital: 'Headshots for your digital life' },
  { code: 'C', name: 'Visa & Passport', note: "Sized to each country's official spec", noteDigital: "Sized to each country's official spec" },
];

// pricing (PHP) — digital is a single studio-edited file; print prices live per package
export const PRICE = {
  digital: 149,
  printFrom: 199,
  currency: '₱',
};
